"""Initial migration

Revision ID: ec78fe44b67d
Revises: 
Create Date: 2026-06-24 10:00:11.163923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec78fe44b67d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ODW.ai Auth user reference'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='Agent display name'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Agent email'),
    sa.Column('role', sa.String(length=30), nullable=False, comment='admin, agent, read_only'),
    sa.Column('is_online', sa.Boolean(), nullable=False, comment='Current online status'),
    sa.Column('max_concurrent_conversations', sa.Integer(), nullable=False, comment='Capacity limit'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_agents_online', 'agents', ['is_online'], unique=False, postgresql_where='is_online = true')
    op.create_index('idx_agents_user_id', 'agents', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Event timestamp'),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='ai_decision, data_access, data_deletion, config_change, login, policy_decision, persona_applied'),
    sa.Column('actor_type', sa.String(length=20), nullable=False, comment='ai, agent, admin, system'),
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='Agent or Admin ID (nullable for AI/system)'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='Resource accessed (e.g., conversation, customer)'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action taken (e.g., read, delete, respond)'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Event details (e.g., model used, confidence score)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment="Actor's IP address"),
    sa.Column('previous_hash', sa.String(length=64), nullable=True, comment='Hash of previous log entry (for tamper detection)'),
    sa.Column('hash', sa.String(length=64), nullable=False, comment='Hash of this log entry'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index('idx_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('brand_personas',
    sa.Column('deployment_id', sa.UUID(), nullable=False, comment='Deployment reference'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Persona name'),
    sa.Column('tone', sa.String(length=100), nullable=False, comment='Tone descriptor (warm, formal, playful, professional)'),
    sa.Column('formality_level', sa.String(length=30), nullable=False, comment='casual, neutral, formal'),
    sa.Column('vocabulary_notes', sa.Text(), nullable=True, comment='Custom vocabulary guidance'),
    sa.Column('dos', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Array of 'do' guidelines"),
    sa.Column('donts', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Array of 'don't' guidelines"),
    sa.Column('emoji_policy', sa.String(length=30), nullable=False, comment='none, minimal, moderate, liberal'),
    sa.Column('signature_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of signature phrases'),
    sa.Column('few_shot_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of example conversations for few-shot learning'),
    sa.Column('channel_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Per-channel persona overrides'),
    sa.Column('persona_backend', sa.String(length=30), nullable=False, comment='prompt or lora_adapter'),
    sa.Column('adapter_uri', sa.String(length=500), nullable=True, comment='LoRA/QLoRA adapter URI (when persona_backend = lora_adapter)'),
    sa.Column('adapter_base_model', sa.String(length=100), nullable=True, comment='Expected base model for adapter'),
    sa.Column('adapter_version', sa.String(length=50), nullable=True, comment='Adapter version identifier'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Persona config version'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this persona is currently active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_personas_backend', 'brand_personas', ['persona_backend'], unique=False)
    op.create_index('idx_brand_personas_deployment_active', 'brand_personas', ['deployment_id', 'is_active'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_brand_personas_name', 'brand_personas', ['name'], unique=False)
    op.create_table('customers',
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Customer display name'),
    sa.Column('channel_identifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Map of channel → identifier (e.g., {"whatsapp": "+1234567890"})'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom metadata (tags, notes)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_channel_identifiers', 'customers', ['channel_identifiers'], unique=False, postgresql_using='gin')
    op.create_index('idx_customers_created_at', 'customers', ['created_at'], unique=False)
    op.create_table('license_state',
    sa.Column('license_key', sa.String(length=500), nullable=False, comment='License key (encrypted at rest)'),
    sa.Column('tier', sa.String(length=30), nullable=False, comment='free, paid'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='active, expired, grace_period, invalid'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='License expiry date'),
    sa.Column('grace_period_ends', sa.DateTime(timezone=True), nullable=True, comment='Grace period expiry'),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Enabled features map'),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=False, comment='Last successful validation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_policies',
    sa.Column('deployment_id', sa.UUID(), nullable=False, comment='Deployment reference'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Policy name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable description'),
    sa.Column('trigger_type', sa.String(length=30), nullable=False, comment='keyword, classifier, llm_intent'),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Trigger configuration'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='template, redirect, inject_context, append_disclaimer, block, escalate'),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Action-specific payload'),
    sa.Column('applies_to', sa.String(length=20), nullable=False, comment='pre, post, both'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Evaluation order (lower = higher priority)'),
    sa.Column('restricted_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of restricted topic labels'),
    sa.Column('allow_general_knowledge_fallback', sa.Boolean(), nullable=False, comment='Whether to allow LLM general knowledge when no Vault doc found'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this policy is currently active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_response_policies_applies_to', 'response_policies', ['applies_to'], unique=False)
    op.create_index('idx_response_policies_deployment_active', 'response_policies', ['deployment_id', 'is_active', 'priority'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_response_policies_trigger_type', 'response_policies', ['trigger_type'], unique=False)
    op.create_table('ai_configurations',
    sa.Column('deployment_id', sa.UUID(), nullable=False, comment='One config per deployment'),
    sa.Column('local_model_endpoint', sa.String(length=500), nullable=True, comment='Ollama/vLLM endpoint URL'),
    sa.Column('local_model_name', sa.String(length=100), nullable=True, comment='Model identifier (e.g., llama-3.1-8b)'),
    sa.Column('frontier_provider', sa.String(length=50), nullable=True, comment='openai, anthropic'),
    sa.Column('frontier_model_name', sa.String(length=100), nullable=True, comment='e.g., gpt-4o, claude-3.5-sonnet'),
    sa.Column('frontier_api_key_encrypted', postgresql.BYTEA(), nullable=True, comment='Encrypted API key'),
    sa.Column('routing_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Routing rules (complexity threshold, PII policy)'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='Base system prompt for AI'),
    sa.Column('confidence_threshold', sa.Float(), nullable=False, comment='Global default confidence threshold'),
    sa.Column('vault_collection_id', sa.UUID(), nullable=True, comment='Default Vault collection for retrieval'),
    sa.Column('pii_shield_enabled', sa.Boolean(), nullable=False, comment='Enable PII detection'),
    sa.Column('pii_frontier_allowed_with_redaction', sa.Boolean(), nullable=False, comment='Allow frontier if PII redacted'),
    sa.Column('active_persona_id', sa.UUID(), nullable=True, comment='Currently active Brand Persona'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['active_persona_id'], ['brand_personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id')
    )
    op.create_index('idx_ai_configurations_active_persona', 'ai_configurations', ['active_persona_id'], unique=False, postgresql_where='active_persona_id IS NOT NULL')
    op.create_index('idx_ai_configurations_deployment', 'ai_configurations', ['deployment_id'], unique=True)
    op.create_table('conversations',
    sa.Column('customer_id', sa.UUID(), nullable=False, comment='Customer reference'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='Channel type: whatsapp, webchat, email, telegram, discord, slack, signal'),
    sa.Column('channel_conversation_id', sa.String(length=255), nullable=False, comment='Channel-specific conversation/thread ID'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='State: new, active, pending, escalated, resolved, closed'),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True, comment='Human agent (if escalated)'),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False, comment='Whether AI auto-responds'),
    sa.Column('confidence_threshold', sa.Float(), nullable=False, comment='Minimum confidence for AI response'),
    sa.Column('sla_first_response_due', sa.DateTime(timezone=True), nullable=True, comment='SLA deadline for first response'),
    sa.Column('sla_resolution_due', sa.DateTime(timezone=True), nullable=True, comment='SLA deadline for resolution'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Channel-specific metadata'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'channel_conversation_id', name='uq_conversations_channel_conversation_id')
    )
    op.create_index('idx_conversations_assigned_agent', 'conversations', ['assigned_agent_id'], unique=False, postgresql_where='assigned_agent_id IS NOT NULL')
    op.create_index('idx_conversations_customer_status', 'conversations', ['customer_id', 'status', 'updated_at'], unique=False)
    op.create_index('idx_conversations_status', 'conversations', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='Conversation reference'),
    sa.Column('sender_type', sa.String(length=20), nullable=False, comment='customer, ai, agent, system'),
    sa.Column('sender_id', sa.String(length=255), nullable=True, comment="Agent ID or 'ai' or customer channel ID"),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text (may be encrypted for PII)'),
    sa.Column('content_redacted', sa.Text(), nullable=True, comment='Redacted version (if PII detected)'),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of media file URLs'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI metadata: model, confidence, routing decision'),
    sa.Column('pii_detected', sa.Boolean(), nullable=False, comment='Whether PII was detected'),
    sa.Column('pii_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of PII types found'),
    sa.Column('channel_message_id', sa.String(length=255), nullable=True, comment='Channel-specific message ID (for dedup)'),
    sa.Column('persona_id', sa.UUID(), nullable=True, comment='Brand Persona used for this message (if AI-generated)'),
    sa.Column('persona_backend_used', sa.String(length=20), nullable=True, comment='prompt or lora_adapter — which persona backend generated this'),
    sa.Column('policy_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Array of policy decisions: [{policy_id, action, matched_on, timestamp}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Message timestamp'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique identifier (UUID)'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['brand_personas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_channel_message_id', 'messages', ['conversation_id', 'channel_message_id'], unique=True, postgresql_where='channel_message_id IS NOT NULL')
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_persona_id', 'messages', ['persona_id'], unique=False, postgresql_where='persona_id IS NOT NULL')
    op.create_index('idx_messages_policy_triggers', 'messages', ['policy_triggers'], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_sender_type', 'messages', ['sender_type'], unique=False, postgresql_where="sender_type = 'ai'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_sender_type', table_name='messages', postgresql_where="sender_type = 'ai'")
    op.drop_index('idx_messages_policy_triggers', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_persona_id', table_name='messages', postgresql_where='persona_id IS NOT NULL')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_index('idx_messages_channel_message_id', table_name='messages', postgresql_where='channel_message_id IS NOT NULL')
    op.drop_table('messages')
    op.drop_index('idx_conversations_status', table_name='conversations')
    op.drop_index('idx_conversations_customer_status', table_name='conversations')
    op.drop_index('idx_conversations_assigned_agent', table_name='conversations', postgresql_where='assigned_agent_id IS NOT NULL')
    op.drop_table('conversations')
    op.drop_index('idx_ai_configurations_deployment', table_name='ai_configurations')
    op.drop_index('idx_ai_configurations_active_persona', table_name='ai_configurations', postgresql_where='active_persona_id IS NOT NULL')
    op.drop_table('ai_configurations')
    op.drop_index('idx_response_policies_trigger_type', table_name='response_policies')
    op.drop_index('idx_response_policies_deployment_active', table_name='response_policies', postgresql_where='is_active = true')
    op.drop_index('idx_response_policies_applies_to', table_name='response_policies')
    op.drop_table('response_policies')
    op.drop_table('license_state')
    op.drop_index('idx_customers_created_at', table_name='customers')
    op.drop_index('idx_customers_channel_identifiers', table_name='customers', postgresql_using='gin')
    op.drop_table('customers')
    op.drop_index('idx_brand_personas_name', table_name='brand_personas')
    op.drop_index('idx_brand_personas_deployment_active', table_name='brand_personas', postgresql_where='is_active = true')
    op.drop_index('idx_brand_personas_backend', table_name='brand_personas')
    op.drop_table('brand_personas')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_agents_user_id', table_name='agents')
    op.drop_index('idx_agents_online', table_name='agents', postgresql_where='is_online = true')
    op.drop_table('agents')
    # ### end Alembic commands ###
